### ISSUE TITLE
Comments for your DG

### ISSUE THREAD

**Issue by MeLoveCarbs** [AY2021S1-CS2113T-F14-3/tp#149]
- [x] This diagram and all other similar diagrams are presumably generated from intelliJ? My suggestion is to draw out only the important classes which would aid in your explanations and leave out any other unnecessary classes which isn't useful in getting your points across to other developers. This applies to other diagrams as well. Try to de-clutter it :) 
![Capture](https://user-images.githubusercontent.com/36870088/97673585-f9b27100-1ac6-11eb-813f-993e6dbf3dd7.PNG)
- [x] The user object should probably not have a lifeline while the Duke class should be activated all the way instead. Is printDineResult() a static method? otherwise the UI object should be instantiated before calling the method.
![Capture1](https://user-images.githubusercontent.com/36870088/97673764-46964780-1ac7-11eb-8ad2-690ce82ce644.PNG)
- [x] The loop should be within FavList and Fav only if it doesn't interact with UI
![Capture2](https://user-images.githubusercontent.com/36870088/97673942-97a63b80-1ac7-11eb-8d37-1c0ed2b9566f.PNG)
- [x] As a side note, it is perfectly fine to leave out a few get/set methods in your UMLs and only show the important methods that aids your explanation. In general, draw the class diagram yourselves whenever possible since the auto generated diagrams is very cluttered as it presents your entire classes/interfaces

Otherwise, good job on your DG! Continue keeping up the good effort!

**Comment by wamikamalik** [comment]
Thank you for the feedback! Will work on these soon!
All diagrams have been drawn using plantUML. The .puml files are all stored in docs/DG_Figures/

**Comment by Johnson-Yee** [comment]
Regarding the fourth comment on "The loop should be within FavList and Fav only if it doesn't interact with UI",
you can add in this line "skinparam BoxPadding 20" right after @startuml
